export const BURGER_LOADING = 'BURGER_LOADING';
export const BURGER_ERROR = 'BURGER_ERROR';

export const BURGER_ADD_ITEM = 'BURGER_ADD_ITEM';
export const BURGER_ADD_ITEM_SET = 'BURGER_ADD_ITEM_SET';

export const BURGER_REMOVE_ITEM = 'BURGER_REMOVE_ITEM';
export const BURGER_REMOVE_ITEM_SET = 'BURGER_REMOVE_ITEM_SET';

export const BURGER_GET_ITEMS = 'BURGER_GET_ITEMS';
export const BURGER_GET_ITEMS_SET = 'BURGER_GET_ITEMS_SET';
